### ISSUE TITLE
Module not found error during pip install Pymrmre

### ISSUE THREAD

**Issue by gvpraagh** [bhklab/PymRMRe#11]
I'm trying to install Pymrmre using pip install in my venv. However, I constantly get an error:

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "c:\Users\...\Documents\...\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\Users\...\Documents\...\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\Users\...\Documents\...\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\...\AppData\Local\Temp\pip-build-env-9s98om71\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\...\AppData\Local\Temp\pip-build-env-9s98om71\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\...\AppData\Local\Temp\pip-build-env-9s98om71\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\...\AppData\Local\Temp\pip-build-env-9s98om71\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

I have already tried removing my venv and installing Cython first. I've also tried to download an older version of Cython (3.0.2 and 0.29.36). But it looks like the problem is not in my venv, but it cannot find Cython somewhere else. Why is it not just building from my venv?

Does anyone know how to solve this issue?

Python version 3.10.11

**Comment by gvpraagh** [comment]
So I found the solution. If anyone ever runs into this: use python 3.8...
